[package]
name = "graphql-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
async-graphql = "7"
async-graphql-actix-web = "7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
lazy_static = "1.5.0"
